# Project information
site_name: ZubZet
site_url: https://zubzet.com/docs
site_author: Alexander Zierhut
site_description: A modular, prototyping speed oriented PHP framework.

# Repository
repo_name: zubzet/framework
repo_url: https://github.com/zubzet/framework/blob/##CI_ENVIROMENT_BRANCH##
edit_uri: docs/

# Copyright
copyright: Copyright &copy; 2018 - 2024 Zierhut IT GmbH - Alexander Zierhut and all ZubZet contributors

# Theme
theme:
    name: 'material'
    palette:
        primary: md-primary-fg-color
        accent: md-primary-fg-color--light
    highlightjs: true
    hljs_languages:
        - php
        - js
        - css
        - html
        - sql
    features:
        - navigation.instant
        - content.action.edit


# Social icons
extra:
    social:
      - icon: fontawesome/solid/paper-plane
        link: mailto:info@zierhut-it.de
        name: Contact via mail
      - icon: fontawesome/brands/twitter
        link: https://x.com/zierhut_it
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/30680659/
      - icon: fontawesome/brands/github
        link: https://github.com/zubzet
    
extra_css:
  - stylesheets/extra.css
# Extensions
markdown_extensions:
    - toc:
        permalink: âš“
    - markdown.extensions.admonition
    - markdown.extensions.abbr
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Navigation
nav:
    - Getting Started: index.md
    - Setup: 
        - Installation: setup/installation.md
        - How To Update: setup/how-to-update.md
        - How to Upgrade: 
            - 0.10.x to 0.11.x: setup/upgrade/0.10.x-to-0.11.x.md
            - 0.9.x to 0.10.x: setup/upgrade/0.9.x-to-0.10.x.md
    - Core Features:
        - MVC:  core-features/mvc.md
        - Controllers And Actions: core-features/controllers-and-actions.md
        - Models: core-features/models.md
        - Views: core-features/views.md
        - Layouts: core-features/layouts.md
        - Permission System: core-features/permission-system.md
        - Localization: core-features/localization.md
        - Configuration: core-features/configuration.md
        - REST API: core-features/rest-api.md
        - Parameter Abstraction: core-features/parameter-abstraction.md
    - Z-Admin:
        - Genral Usage: z-admin/usage.md
        - Login as another User: z-admin/login-as-another-user.md
    - Forms:
        - Auto Validation: forms/auto-form-validation.md
        - CED Validation: forms/ced-validation.md
        - File Uploads: forms/file-uploads.md
    - Frontend Integration:
        - Backend Requests: frontend-integration/backend-requests.md
        - Presets: frontend-integration/presets.md
    - Template Rendering Usages:
        - Generating PDFs: template-rendering-usages/generating-pdfs.md
        - Sending Mails: template-rendering-usages/sending-an-email.md
    - Advanced Features:
        - Sitemap Generation: advanced-features/sitemap-generation.md
        - Aliases And Virtual Links: advanced-features/aliases-and-virtual-links.md
        - Commands: advanced-features/commands.md