# Project information
site_name: ZubZet
site_url: https://zubzet.com/docs/
site_author: Alexander Zierhut
site_description: A modular, prototyping speed oriented PHP framework.

# Repository
repo_name: zubzet/framework
repo_url: https://github.com/zubzet/framework
edit_uri: docs/

# Copyright
copyright: ZubZet contributors

# Theme
theme:
    name: 'material'
    palette:
        primary: md-primary-fg-color
        accent: md-primary-fg-color--light
    highlightjs: true
    hljs_languages:
        - php
        - js
        - css
        - html
        - sql
    features:
        - navigation.instant
        - content.action.edit


# Social icons
extra:
    social:
      - icon: fontawesome/solid/paper-plane
        link: mailto:info@zierhut-it.de
        name: Contact via mail
      - icon: fontawesome/brands/twitter
        link: https://x.com/zierhut_it
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/30680659/
      - icon: fontawesome/brands/github
        link: https://github.com/zubzet
    version:
        provider: mike
        alias: true

# Plugins
plugins:
    - search

use_directory_urls: true

extra_css:
  - stylesheets/extra.css

# MD Extensions
markdown_extensions:
    - toc:
        permalink: âš“
    - markdown.extensions.admonition
    - markdown.extensions.abbr
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: zubzet
        repo: framework
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

# Navigation
nav:
    - Getting Started: index
    - Setup:
        - Installation: setup/installation
        - How To Contribute: setup/how-to-contribute
        - How To Update: setup/how-to-update
        - How to Upgrade:
            - 0.11 to 1.0.0: setup/upgrade/0.11-to-1.0.0
            - 0.10 to 0.11: setup/upgrade/0.10-to-0.11
            - 0.9 to 0.10: setup/upgrade/0.9-to-0.10
    - Core Features:
        - MVC:  core-features/mvc
        - Controllers And Actions: core-features/controllers-and-actions
        - Models: core-features/models
        - Views: core-features/views
        - Layouts: core-features/layouts
        - Permission System: core-features/permission-system
        - Localization: core-features/localization
        - Configuration: core-features/configuration
        - REST API: core-features/rest-api
        - Parameter Abstraction: core-features/parameter-abstraction
        - Routing: core-features/routing
        - QueryBuilder: core-features/query-builder
    - Z-Admin:
        - Genral Usage: z-admin/usage
        - Login as another User: z-admin/login-as-another-user
    - Forms:
        - Auto Validation: forms/auto-form-validation
        - CED Validation: forms/ced-validation
        - File Uploads: forms/file-uploads
    - Frontend Integration:
        - Backend Requests: frontend-integration/backend-requests
        - Presets: frontend-integration/presets
    - Template Rendering Usages:
        - Sending Mails: template-rendering-usages/sending-an-email
    - Advanced Features:
        - Aliases And Virtual Links: advanced-features/aliases-and-virtual-links
        - Commands: advanced-features/commands
    - API Reference: api/index.html
    - Guides:
        - Guest List: guides/guest-list
        - Library: guides/library
        - Shop: guides/shop
        - Todo: guides/todo
        - Layouts: guides/layout
        - Emails: guides/email